version: 2.1

orbs:
  node: circleci/node@4.1
  blackduck: signavio/blackduck@1.3.0
  fortify: signavio/fortify@1.0.0

references:
  workspace_root: &workspace_root ~/repo

executors:
  fortify:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: 2xlarge

jobs:
  build-and-black-duck-scan:
    working_directory: *workspace_root
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run build
          command: yarn build
      - blackduck/blackduck-detect:
          blackduck-project-group: SAP_PROCESS_MANAGER_OD_2.0
          blackduck-project-name: binge
          blackduck-project-path: *workspace_root

  fortify-translate-and-scan:
    executor: fortify
    working_directory: *workspace_root
    steps:
      - checkout
      - fortify/setup
      - run:
          name: Translate Binge
          command: |
            set -x
            sourceanalyzer \
              -b binge \
              -verbose \
              ./src
      - run:
          name: Analyze Binge
          command: |
            sourceanalyzer \
              -b binge \
              -verbose \
              -scan \
              -f binge.fpr
      - store_artifacts:
          path: binge.fpr

workflows:
  black-duck-scan:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build-and-black-duck-scan:
          context: BlackDuck
  fortify-workflow:
    # triggers:
    #   - schedule:
    #       cron: "0 0 * * *"
    #       filters:
    #         branches:
    #           only: master
    jobs:
      - fortify-translate-and-scan:
          context:
            - fortify
